Avoid error when no `Accept-Language` header is provided
Previously the following error would occur when a request was received
without an 'Accept-Language' header:

```
RangeError: Incorrect locale information provided
    at Intl.getCanonicalLocales (<anonymous>)
    at <unknown> (src/i18n/request.ts:13:23)
  11 |     },
  12 |   }).languages();
> 13 |   const locale = match(languages, ["en", "fr"], "en");
```

This would have caused issues with Playwright's web server option [1] as
the requests made to check whether the web server is ready to accept
connections do not include an 'Accept-Language' header, and would
therefore have always received an HTTP 500 error response.

[1] https://playwright.dev/docs/test-webserver#configuring-a-web-server